name: Android CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
    - name: "Build Android project"
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "./gradlew assembleDebug"
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "test@test.com"
        git config --local user.name "test123"
        git commit -m "ci: Automated build push" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
