name: Better-Tree Workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  better-tree-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Better-Tree Action
        uses: MRfantastic3DGamer/Better-Tree-Action@v0.1.2-alpha
        with:
          root: "~/work/Angular-Apps/Angular-Apps/project/app"
          doc: "~/work/Angular-Apps/Angular-Apps/project/README.md"
          no-files: "false"
          stack-folders: "false"
          show-hidden: "false"
          ignored-locations: "gradle/"
