name: Generate Directory Pattern

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ./project

      - name: Create Better-Tree Directory
        run: mkdir -p ./better-tree

      - name: Clone Better-Tree Repository
        run: git clone https://github.com/MRfantastic3DGamer/Better-Tree.git ./better-tree

      - name: Debug Information
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the project directory:"
          ls -R ./project
          echo "Contents of the better-tree directory:"
          ls -R ./better-tree

      - name: Check Directory Paths
        run: |
          echo "Checking if directories exist:"
          if [ -d ./project ]; then echo "./project exists"; else echo "./project does not exist"; fi
          if [ -f ./project/README.md ]; then echo "./project/README.md is a file"; else echo "./project/README.md is not a file"; fi

      - name: Run Better-Tree Executable
        run: |
          tree ~/work/ -d
          ABSOLUTE_PROJECT_PATH=$(pwd)/project
          ABSOLUTE_README_PATH=$(pwd)/project/README.md
          echo "Running better-tree executable with:"
          echo "Project Path: $ABSOLUTE_PROJECT_PATH"
          echo "README Path: $ABSOLUTE_README_PATH"
          ./better-tree/executables/better-tree -- ~/work/ ~/work/Angular-Apps/Angular-Apps/project/README.md
