name: Generate Directory Pattern

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ./project

      - name: Create Better-Tree Directory
        run: |
          su
          mkdir -p ./better-tree

      - name: Get Better-Tree
        run: curl -L -o better-tree https://raw.githubusercontent.com/MRfantastic3DGamer/Better-Tree/main/executables/better-tree

      - name: Better-Tree set up
        run: chmod +x better-tree

      - name: Run Better-Tree Executable
        run: |
          ./better-tree ./app 

      - name: Push updated docs
        working-directory: ./project
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "[bot]Update Folder Structure"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
