name: Generate Directory Pattern

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ./project

      - name: Create Better-Tree Directory
        run: mkdir -p ./better-tree

      - name: Clone Better-Tree Repository
        run: git clone https://github.com/MRfantastic3DGamer/Better-Tree.git ./better-tree

      - name: Debug Information
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the project directory:"
          ls -R ./project
          echo "Contents of the better-tree directory:"
          ls -R ./better-tree
      - name: Check Executable
        run: |
          if [ -x ./better-tree/executables/better-tree ]; then
            echo "Executable found and is executable"
          else
            echo "Executable not found or not executable"
            exit 1
          fi
      - name: Run Better-Tree Executable
        run: |
          echo "Running better-tree executable..."
          ./better-tree/executables/better-tree -- ./project ./project/README.md
