name: Generate Directory Pattern

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          pwd
          tree
          tree ./
          ls
      - name: Checkout Repository
        uses: MRfantastic3DGamer/Better-Tree-Action@v0.1.9-alpha
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          root: "./"
          auto-doc: true
          ignored-locations: |
            "./project/src/test"
