name: Generate Directory Pattern

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: MRfantastic3DGamer/Better-Tree-Action@v0.1.4-alpha
        with:
          root: "./"
