name: Generate Directory Pattern

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Debug
        run: |
          pwd
          tree
          tree ./
          ls
      - name: Checkout Repository
        uses: MRfantastic3DGamer/Better-Tree-Action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          root: "./"
          auto-doc: true
          ignored-locations: "./gradle ./app/src/test ./app/src/androidTest ./app/src/main/res ./app/release"
