name: Generate Directory Pattern
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: ./project

      - name: Create Better-Tree Directory
        run: mkdir -p ./better-tree

      - name: Clone Better-Tree Repository
        run: git clone https://github.com/MRfantastic3DGamer/Better-Tree.git ./better-tree
      - name: final
        run: tree
      - name: create pattern
        run: ./better-tree/executables/better-tree -- /project /project/README.md
