name: Generate Directory Pattern
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Generate:
    runs-on: ubuntu-latest
    steps:
      - name: original content
        run: ls
      - uses: actions/checkout@v4
      - name: content after checkout
        run: ls
      - name: move content to project directory
        run: | 
          mkdir project
          ll
      - uses: sudosubin/git-clone-action@v1.0.1
        with:
          repository: MRfantastic3DGamer/Better-Tree
          # Relative path from current directory, where to clone.
          path: ./better-tree/
      - name: content
        run: ls
